# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/triggerkit',
                'doc_host': 'https://Datatistics.github.io',
                'git_url': 'https://github.com/Datatistics/triggerkit',
                'lib_path': 'triggerkit'},
  'syms': {'triggerkit.core': {'triggerkit.core.foo': ('core.html#foo', 'triggerkit/core.py')}}}
