project:
  type: website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
  announcement: 
    icon: wrench-adjustable-circle-fill
    dismissable: true
    content: "**Alert** - In active development and not ready for public use. Should be ready in a week or two!"
    type: info
    position: below-navbar
metadata-files: [nbdev.yml, sidebar.yml]