project:
  type: website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

website:
  repo-url: https://github.com/Datatistics/triggerkit
  repo-subdir: nbs
  repo-actions: [edit, issue]
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.ipynb
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Tutorials
        contents: Tutorials/*
      - section: Explanations
        contents: Explanations/*
      - section: API
        contents: API/*
  announcement: 
    icon: wrench-adjustable-circle-fill
    dismissable: true
    content: "TriggerKit is in active development and not ready for public use. Should be ready in a week or two!"
    type: info
    position: below-navbar
metadata-files: [nbdev.yml]